### ISSUE TITLE
[Build error] about Qt5

### ISSUE THREAD

**Issue by CaptainEven** [mehrab2603/scan3d-capture#1]
Thanks for your excellent contribution! An error  occured when building the project as follows:
```
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

```

**Comment by CaptainEven** [comment]
@mehrab2603 How to config QT5 after QT5's installation?

**Comment by mehrab2603** [comment]
If QT5 is in your path, I think CMake should be able to pick it up automatically. Otherwise, please try following what the error message instructs (ie. set "Qt5_DIR" to a directory containing one of the above files).

**Comment by CaptainEven** [comment]
@mehrab2603 Thanks for your advice! I'll try it.

**Comment by CaptainEven** [comment]
@mehrab2603 QT5 configuration succeeded, but another error occured:
```
CMake Error at cmake/Modules/FindSpinnaker.cmake:73 (MESSAGE):
  Could not find the Spinnaker library
Call Stack (most recent call first):
  CMakeLists.txt:54 (find_package)

```

**Comment by CaptainEven** [comment]
The problem solved by removing the Spinnaker CMake configs in CMakeFileList.

**Comment by mehrab2603** [comment]
If you didn't want Spinnaker, all you had to do was set WITH_SPINNAKER=OFF when configuring with CMake. If you have WITH_SPINNAKER=ON when configuring, you must make sure that Spinnaker is installed and is in your path.
